# Generated by Django 2.1.2 on 2018-10-22 14:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('visibility', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], max_length=16)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection_Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_id', models.CharField(max_length=60)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('added_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evodraw.Collection')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='evodraw.Collection')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
