# Generated by Django 2.1.2 on 2018-11-01 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evodraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_individual',
            name='visibility',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='Public', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collection_individual',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
