# Generated by Django 2.1.2 on 2018-10-22 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evodraw', '0002_auto_20181022_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_individual',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
